/* automatically generated by rust-bindgen 0.57.0 */

pub const basisu_texture_format_cInvalidTextureFormat: basisu_texture_format = -1;
pub const basisu_texture_format_cETC1: basisu_texture_format = 0;
pub const basisu_texture_format_cETC1S: basisu_texture_format = 1;
pub const basisu_texture_format_cETC2_RGB: basisu_texture_format = 2;
pub const basisu_texture_format_cETC2_RGBA: basisu_texture_format = 3;
pub const basisu_texture_format_cETC2_ALPHA: basisu_texture_format = 4;
pub const basisu_texture_format_cBC1: basisu_texture_format = 5;
pub const basisu_texture_format_cBC3: basisu_texture_format = 6;
pub const basisu_texture_format_cBC4: basisu_texture_format = 7;
pub const basisu_texture_format_cBC5: basisu_texture_format = 8;
pub const basisu_texture_format_cBC7: basisu_texture_format = 9;
pub const basisu_texture_format_cASTC4x4: basisu_texture_format = 10;
pub const basisu_texture_format_cPVRTC1_4_RGB: basisu_texture_format = 11;
pub const basisu_texture_format_cPVRTC1_4_RGBA: basisu_texture_format = 12;
pub const basisu_texture_format_cATC_RGB: basisu_texture_format = 13;
pub const basisu_texture_format_cATC_RGBA_INTERPOLATED_ALPHA: basisu_texture_format = 14;
pub const basisu_texture_format_cFXT1_RGB: basisu_texture_format = 15;
pub const basisu_texture_format_cPVRTC2_4_RGBA: basisu_texture_format = 16;
pub const basisu_texture_format_cETC2_R11_EAC: basisu_texture_format = 17;
pub const basisu_texture_format_cETC2_RG11_EAC: basisu_texture_format = 18;
pub const basisu_texture_format_cUASTC4x4: basisu_texture_format = 19;
pub const basisu_texture_format_cBC1_NV: basisu_texture_format = 20;
pub const basisu_texture_format_cBC1_AMD: basisu_texture_format = 21;
pub const basisu_texture_format_cRGBA32: basisu_texture_format = 22;
pub const basisu_texture_format_cRGB565: basisu_texture_format = 23;
pub const basisu_texture_format_cBGR565: basisu_texture_format = 24;
pub const basisu_texture_format_cRGBA4444: basisu_texture_format = 25;
pub const basisu_texture_format_cABGR4444: basisu_texture_format = 26;
pub type basisu_texture_format = ::std::os::raw::c_int;
pub const basist_block_format_cETC1: basist_block_format = 0;
pub const basist_block_format_cETC2_RGBA: basist_block_format = 1;
pub const basist_block_format_cBC1: basist_block_format = 2;
pub const basist_block_format_cBC3: basist_block_format = 3;
pub const basist_block_format_cBC4: basist_block_format = 4;
pub const basist_block_format_cBC5: basist_block_format = 5;
pub const basist_block_format_cPVRTC1_4_RGB: basist_block_format = 6;
pub const basist_block_format_cPVRTC1_4_RGBA: basist_block_format = 7;
pub const basist_block_format_cBC7: basist_block_format = 8;
pub const basist_block_format_cBC7_M5_COLOR: basist_block_format = 9;
pub const basist_block_format_cBC7_M5_ALPHA: basist_block_format = 10;
pub const basist_block_format_cETC2_EAC_A8: basist_block_format = 11;
pub const basist_block_format_cASTC_4x4: basist_block_format = 12;
pub const basist_block_format_cATC_RGB: basist_block_format = 13;
pub const basist_block_format_cATC_RGBA_INTERPOLATED_ALPHA: basist_block_format = 14;
pub const basist_block_format_cFXT1_RGB: basist_block_format = 15;
pub const basist_block_format_cPVRTC2_4_RGB: basist_block_format = 16;
pub const basist_block_format_cPVRTC2_4_RGBA: basist_block_format = 17;
pub const basist_block_format_cETC2_EAC_R11: basist_block_format = 18;
pub const basist_block_format_cETC2_EAC_RG11: basist_block_format = 19;
pub const basist_block_format_cIndices: basist_block_format = 20;
pub const basist_block_format_cRGB32: basist_block_format = 21;
pub const basist_block_format_cRGBA32: basist_block_format = 22;
pub const basist_block_format_cA32: basist_block_format = 23;
pub const basist_block_format_cRGB565: basist_block_format = 24;
pub const basist_block_format_cBGR565: basist_block_format = 25;
pub const basist_block_format_cRGBA4444_COLOR: basist_block_format = 26;
pub const basist_block_format_cRGBA4444_ALPHA: basist_block_format = 27;
pub const basist_block_format_cRGBA4444_COLOR_OPAQUE: basist_block_format = 28;
pub const basist_block_format_cRGBA4444: basist_block_format = 29;
pub const basist_block_format_cTotalBlockFormats: basist_block_format = 30;
pub type basist_block_format = ::std::os::raw::c_int;
pub const basist_basis_texture_type_cBASISTexType2D: basist_basis_texture_type = 0;
pub const basist_basis_texture_type_cBASISTexType2DArray: basist_basis_texture_type = 1;
pub const basist_basis_texture_type_cBASISTexTypeCubemapArray: basist_basis_texture_type = 2;
pub const basist_basis_texture_type_cBASISTexTypeVideoFrames: basist_basis_texture_type = 3;
pub const basist_basis_texture_type_cBASISTexTypeVolume: basist_basis_texture_type = 4;
pub const basist_basis_texture_type_cBASISTexTypeTotal: basist_basis_texture_type = 5;
pub type basist_basis_texture_type = ::std::os::raw::c_uint;
pub const basist_basis_tex_format_cETC1S: basist_basis_tex_format = 0;
pub const basist_basis_tex_format_cUASTC4x4: basist_basis_tex_format = 1;
pub type basist_basis_tex_format = ::std::os::raw::c_int;
pub const basist_transcoder_texture_format_cTFETC1_RGB: basist_transcoder_texture_format = 0;
pub const basist_transcoder_texture_format_cTFETC2_RGBA: basist_transcoder_texture_format = 1;
pub const basist_transcoder_texture_format_cTFBC1_RGB: basist_transcoder_texture_format = 2;
pub const basist_transcoder_texture_format_cTFBC3_RGBA: basist_transcoder_texture_format = 3;
pub const basist_transcoder_texture_format_cTFBC4_R: basist_transcoder_texture_format = 4;
pub const basist_transcoder_texture_format_cTFBC5_RG: basist_transcoder_texture_format = 5;
pub const basist_transcoder_texture_format_cTFBC7_RGBA: basist_transcoder_texture_format = 6;
pub const basist_transcoder_texture_format_cTFPVRTC1_4_RGB: basist_transcoder_texture_format = 8;
pub const basist_transcoder_texture_format_cTFPVRTC1_4_RGBA: basist_transcoder_texture_format = 9;
pub const basist_transcoder_texture_format_cTFASTC_4x4_RGBA: basist_transcoder_texture_format = 10;
pub const basist_transcoder_texture_format_cTFATC_RGB: basist_transcoder_texture_format = 11;
pub const basist_transcoder_texture_format_cTFATC_RGBA: basist_transcoder_texture_format = 12;
pub const basist_transcoder_texture_format_cTFFXT1_RGB: basist_transcoder_texture_format = 17;
pub const basist_transcoder_texture_format_cTFPVRTC2_4_RGB: basist_transcoder_texture_format = 18;
pub const basist_transcoder_texture_format_cTFPVRTC2_4_RGBA: basist_transcoder_texture_format = 19;
pub const basist_transcoder_texture_format_cTFETC2_EAC_R11: basist_transcoder_texture_format = 20;
pub const basist_transcoder_texture_format_cTFETC2_EAC_RG11: basist_transcoder_texture_format = 21;
pub const basist_transcoder_texture_format_cTFRGBA32: basist_transcoder_texture_format = 13;
pub const basist_transcoder_texture_format_cTFRGB565: basist_transcoder_texture_format = 14;
pub const basist_transcoder_texture_format_cTFBGR565: basist_transcoder_texture_format = 15;
pub const basist_transcoder_texture_format_cTFRGBA4444: basist_transcoder_texture_format = 16;
pub const basist_transcoder_texture_format_cTFTotalTextureFormats:
    basist_transcoder_texture_format = 22;
pub const basist_transcoder_texture_format_cTFETC1: basist_transcoder_texture_format = 0;
pub const basist_transcoder_texture_format_cTFETC2: basist_transcoder_texture_format = 1;
pub const basist_transcoder_texture_format_cTFBC1: basist_transcoder_texture_format = 2;
pub const basist_transcoder_texture_format_cTFBC3: basist_transcoder_texture_format = 3;
pub const basist_transcoder_texture_format_cTFBC4: basist_transcoder_texture_format = 4;
pub const basist_transcoder_texture_format_cTFBC5: basist_transcoder_texture_format = 5;
pub const basist_transcoder_texture_format_cTFBC7_M6_RGB: basist_transcoder_texture_format = 6;
pub const basist_transcoder_texture_format_cTFBC7_M5_RGBA: basist_transcoder_texture_format = 6;
pub const basist_transcoder_texture_format_cTFBC7_M6_OPAQUE_ONLY: basist_transcoder_texture_format =
    6;
pub const basist_transcoder_texture_format_cTFBC7_M5: basist_transcoder_texture_format = 6;
pub const basist_transcoder_texture_format_cTFBC7_ALT: basist_transcoder_texture_format = 7;
pub const basist_transcoder_texture_format_cTFASTC_4x4: basist_transcoder_texture_format = 10;
pub const basist_transcoder_texture_format_cTFATC_RGBA_INTERPOLATED_ALPHA:
    basist_transcoder_texture_format = 12;
pub type basist_transcoder_texture_format = ::std::os::raw::c_int;
extern "C" {
    pub fn basis_get_bytes_per_block_or_pixel(fmt: basist_transcoder_texture_format) -> u32;
}
extern "C" {
    pub fn basis_get_format_name(
        fmt: basist_transcoder_texture_format,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn basis_get_block_format_name(fmt: basist_block_format) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn basis_transcoder_format_has_alpha(fmt: basist_transcoder_texture_format) -> bool;
}
extern "C" {
    pub fn basis_get_basisu_texture_format(
        fmt: basist_transcoder_texture_format,
    ) -> basisu_texture_format;
}
extern "C" {
    pub fn basis_get_texture_type_name(
        tex_type: basist_basis_texture_type,
    ) -> *const ::std::os::raw::c_char;
}
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Copy, Clone)]
pub struct Transcoder {
    pub _bindgen_opaque_blob: [u64; 2usize],
}
#[test]
fn bindgen_test_layout_Transcoder() {
    assert_eq!(
        ::std::mem::size_of::<Transcoder>(),
        16usize,
        concat!("Size of: ", stringify!(Transcoder))
    );
    assert_eq!(
        ::std::mem::align_of::<Transcoder>(),
        8usize,
        concat!("Alignment of ", stringify!(Transcoder))
    );
}
extern "C" {
    pub fn transcoder_new() -> *mut Transcoder;
}
extern "C" {
    pub fn transcoder_delete(transcoder: *mut Transcoder);
}
extern "C" {
    pub fn transcoder_get_total_images(
        transcoder: *const Transcoder,
        pData: *const ::std::os::raw::c_void,
        data_size: u32,
    ) -> u32;
}
extern "C" {
    pub fn transcoder_get_tex_format(
        transcoder: *const Transcoder,
        pData: *const ::std::os::raw::c_void,
        data_size: u32,
    ) -> basist_basis_tex_format;
}
extern "C" {
    pub fn transcoder_get_total_image_levels(
        transcoder: *const Transcoder,
        pData: *const ::std::os::raw::c_void,
        data_size: u32,
        image_index: u32,
    ) -> u32;
}
extern "C" {
    pub fn transcoder_start_transcoding(
        transcoder: *mut Transcoder,
        pData: *const ::std::os::raw::c_void,
        data_size: u32,
    ) -> bool;
}
extern "C" {
    pub fn transcoder_stop_transcoding(transcoder: *mut Transcoder) -> bool;
}
extern "C" {
    pub fn transcoder_get_ready_to_transcode(transcoder: *const Transcoder) -> bool;
}
extern "C" {
    pub fn basisu_transcoder_init();
}
